import { Rubik } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./Components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Next Ticket Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
